apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: openshift-gitops-operator-controller-manager
  name: openshift-gitops-operator-metrics-bearer-token
type: kubernetes.io/service-account-token
