apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitops-operator
  template:
    metadata:
      labels:
        name: gitops-operator
    spec:
      serviceAccountName: gitops-operator
      containers:
        - name: gitops-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - gitops-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitops-operator"
