## Append samples you want in your CSV to this file as resources ##
resources:
- pipelines_v1alpha1_gitopsservice.yaml
- argoproj.io_v1alpha1_argocd.yaml
- argoproj.io_v1alpha1_application.yaml
- argoproj.io_v1alpha1_applicationset.yaml
- argoproj.io_v1alpha1_appproject.yaml
- argoproj.io_v1alpha1_rollout_manager.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
