# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/gitops-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  patch: |-
    # Add ENABLE_CONVERSION_WEBHOOK env to enable conversion webhook
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: "ENABLE_CONVERSION_WEBHOOK"
        value: "true"
    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/containers/1/volumeMounts/0
    # Remove the "cert" volume, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/volumes/0
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: argocds.argoproj.io
  patch: |-
    # Remove Service CA operator annotation
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1inject-cabundle
- target:
    version: v1
    kind: Service
    name: webhook-service
    namespace: system
  patch: |-
    # Remove Service CA operator annotation
    - op: remove
      path: /metadata/annotations/service.beta.openshift.io~1serving-cert-secret-name

patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: gitops-operator.v1.8.0
  path: patches/icon.yaml
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: gitops-operator.v1.8.0
  path: patches/description.yaml